Add $(DEBCFLAGS), remove -O* from CFLAGS in order to support
DEB_BUILD_FLAGS variable in debian/rules

Index: dictd/Makefile.in
===================================================================
--- dictd.orig/Makefile.in	2011-02-13 15:01:41.000000000 +0100
+++ dictd/Makefile.in	2011-02-13 15:03:28.000000000 +0100
@@ -206,7 +206,7 @@
 	$(INSTALL_DATA) dict.1 $(DESTDIR)$(man1_prefix)/ && \
 	$(INSTALL_SCRIPT) dictl $(DESTDIR)$(bindir)/ && \
 	$(INSTALL_DATA) dictl.1 $(DESTDIR)$(man1_prefix)/
-	$(INSTALL_SCRIPT) dict_lookup $(DESTDIR)$(bindir)/ && \
+	$(INSTALL_SCRIPT) $(srcdir)/dict_lookup $(DESTDIR)$(bindir)/ && \
 	$(INSTALL_DATA) dict_lookup.1 $(DESTDIR)$(man1_prefix)/
 
 install.colorit: colorit
@@ -376,7 +376,8 @@
 	-rm -f *.dict *.index
 	-rm -f *.exe *.dll
 	-rm -f test/_* test/testdb.t.txt test/log.txt
-	-rm -f ChangeLog*
+	-rm -f $(patsubst %.in,%,$(wildcard examples/*.in))
+	#-rm -f ChangeLog*
 
 recursive-clean: clean
 	@for subdir in `echo $(subdirs)`; do \
