#!/bin/sh
# $Id: dict.preinst 22 2008-01-19 22:25:57Z robert $

set -e

move_conffile ()
{
       dpkg --compare-versions "$1" ge-nl "1.9.11" && return;
       [ ! -e /etc/dict.conf ] && return;
       [ -e /etc/dictd/dict.conf ] && return;
       [ -d /etc/dictd ] || mkdir /etc/dictd;
       touch /etc/dict.conf.moved_by_preinst;
       mv -v /etc/dict.conf /etc/dictd/dict.conf >&2;
}

case "$1" in
install|upgrade)
       # /etc/dict.conf moved to /etc/dictd/dict.conf in 1.9.11
       move_conffile "$2"
       ;;

abort-upgrade)
       # Postrm has only error handling; nothing to undo
       ;;

*)
       echo "preinst called with unknown argument \`$1'" >&2
       exit 1
       ;;
esac

#DEBHELPER#
