#!/bin/sh
# vim: ts=4:et:sts=4
# $Id: dictd.postrm 89 2009-01-03 16:34:01Z robert $

set -e

PACKAGE=dictd
DEFAULTSFILE=/etc/default/$PACKAGE


cleanupUcf() 
{
    # we mimic dpkg as closely as possible, so we remove configuration
    # files with dpkg backup extensions too:
    for ext in '~' '%' .bak .ucf-new .ucf-old .ucf-dist .dpkg-tmp '';  do
        rm -f "${DEFAULTSFILE}${ext}"
    done
    ! which ucf  >/dev/null || ucf  --purge "$DEFAULTSFILE"
    ! which ucfr >/dev/null || ucfr --purge "$PACKAGE" "$DEFAULTSFILE"
}

#DEBHELPER# 

case "$1" in
   failed-install|abort-install|abort-upgrade|failed-upgrade)
        exit 0
    ;;

    remove)
        rm -fr /var/lib/dictd/
        exit 0
    ;;
    purge)

        rm -f /var/lib/dictd/db.list
        rm -rf /var/lib/dictd/ 
        [ ! -d /etc/dictd ] || rmdir  --ignore-fail-on-non-empty /etc/dictd || true
        cleanupUcf

        # remove inetd entry
        ! which update-inetd >/dev/null || update-inetd --remove "dict" >/dev/null 2>&1 || true

        # remove user, group and home directory dictd
        deluser --remove-home dictd >/dev/null 2>&1 || true

        exit 0
    ;;
    upgrade|disappear)
        exit 0
    ;;
    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 0
    ;;
esac
