#!/bin/sh
# $Id: dictd.postinst 22 2008-01-19 22:25:57Z robert $

set -e

PACKAGE=dictd

case "$1" in 
     configure)
     if [ -e /etc/dictd.conf.moved_by_preinst ]; then 
        rm /etc/dictd.conf.moved_by_preinst;
     fi
     if [ -x /usr/sbin/dictdconfig ]; then dictdconfig -w ;fi

     exit 0
     ;;

    failed-upgrade|abort-upgrade|abort-remove|abort-deconfigure|in-favour|removing)
        exit 0;
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2;
        exit 0;
    ;;
esac

#DEBHELPER#
