#!/bin/sh
# vim: ts=4:et:sts=4
# $Id: dictd.postrm 78 2008-12-31 10:38:05Z robert $

set -e

PACKAGE=dictd
DEFAULTSFILE=/etc/default/$PACKAGE

cleanup () {
  if [ -e /etc/dictd.conf.moved_by_preinst -a -d /etc/dictd ]; then 
    if [ -e /etc/dictd/dictd.conf ]; then
       mv /etc/dictd/dictd.conf /etc/dictd.conf
    fi
    if [ -e /etc/dictd/dictd.order ]; then
       mv /etc/dictd/dictd.order /etc/dictd.order
    fi
    rmdir /etc/dictd/
    rm /etc/dictd.conf.moved by preinst
  fi
}

cleanupUcf() 
{
    which ucf >/dev/null && HAS_UCF=yes || HAS_UCF=no
    which ucfr >/dev/null && HAS_UCFR=yes || HAS_UCFR=no
    # we mimic dpkg as closely as possible, so we remove configuration
    # files with dpkg backup extensions too:
    for ext in '~' '%' .bak .ucf-new .ucf-old .ucf-dist .dpkg-tmp '';  do
        rm -f "${DEFAULTSFILE}${ext}"
    done
    [ "$HAS_UCF"  != "yes"  ] || ucf  --purge "$DEFAULTSFILE"
    [ "$HAS_UCFR" != "yes" ]  || ucfr --purge "$PACKAGE" "$DEFAULTSFILE"
}

#DEBHELPER# 

case "$1" in
   failed-install|abort-install|abort-upgrade|failed-upgrade)
        cleanup
        exit 0
    ;;

    remove)
        rm -fr /var/lib/dictd/
        exit 0
    ;;
    purge)

        rm -f /var/lib/dictd/db.list
        rmdir  --ignore-fail-on-non-empty /etc/dictd || true
        cleanupUcf



        # remove inetd entry
        [ ! -x /usr/sbin/update-inetd ] \
            || update-inetd \
                --remove "dictd\tstream\ttcp\tnowait\tdictd.dictd\t/usr/sbin/tcpd\t/usr/sbin/dictd.*"  \
            || true

        # remove user
        rmdir --ignore-fail-on-non-empty /var/lib/dictd/  || true
# remove user, group and home directory dictd
        deluser --remove-home dictd >/dev/null 2>&1 || true

        exit 0
    ;;
    upgrade|disappear)
        exit 0
    ;;
    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 0
    ;;
esac
