#! /bin/sh
set -e

cleanup ()
{
       [ ! -e /etc/dict.conf.moved_by_preinst ] && return;
       [ -e /etc/dictd/dict.conf ] && mv /etc/dictd/dict.conf /etc/
       [ -e /etc/dictd ] && rmdir /etc/dictd;
       rm /etc/dict.conf.moved_by_preinst
}

case "$1" in
abort-install|abort-upgrade)
       # Undo the effects of preinst install/upgrade.
       cleanup
       ;;

remove|purge|upgrade|failed-upgrade|disappear)
       ;;

*)
       echo "postrm called with unknown argument \`$1'" >&2
       exit 1
       ;;
esac
